packages:
  - .

overrides:
  '@tiptap/core@<3.30.5': ^3.30.5
  brace-expansion@>=2.0.0 <2.1.7: 2.1.7
  devalue@>=5.1.0 <=5.9.2: 5.9.4
  esbuild@0.27.7: 0.28.2
  qs@<6.16.0: ^6.16.0
  serialize-javascript@>=7.1.1 <7.1.2: 7.1.2
  shell-quote@>=1.8.4 <1.11.0: 1.12.0
  simple-git@>=3.15.0 <4.0.1: 4.0.2
  source-map-js@>=1.0.0 <1.2.2: 1.2.2
  svgo@>=4.0.0 <4.1.0: ^4.1.0

onlyBuiltDependencies:
  - esbuild
  - vue-demi

allowBuilds:
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - '@querry-kit/nuxt'
  - qs@6.15.4 || 6.16.0
  - '@tiptap/core@3.30.4 || 3.30.5'
  - svgo@4.1.0

patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
  node-forge@1.4.0: patches/node-forge@1.4.0.patch
